#!/usr/bin/env bash
set -euo pipefail

home="$(realpath "$(realpath "${BASH_SOURCE[0]}" | xargs dirname)"/.)"
cd "$home"
pwd

# project_name=$(basename "$(realpath .)")
# while inotifywait -e close_write lib; do
#   browserify lib/index.js -o "$project_name.browserified.js"
#   date +"%Y-%m-%d %H:%M:%S"
#   done

function build {
  set -x
  yalc update
  browserify -r 'mudom'                           -o 'static/browserified/mudom.js'
  # browserify -r 'intermatic'                      -o 'static/browserified/intermatic.js'
  # browserify -r 'intertype'                       -o 'static/browserified/intertype.js'
  # browserify -r 'cnd'                             -o 'static/browserified/cnd.js'
  # browserify -r 'util'                            -o 'static/browserified/util.js'
  set +x
  }

time build
date +"%Y-%m-%d %H:%M:%S"



