#!/usr/bin/env bash
set -euo pipefail

target_path='/tmp/dpan.txt'

echo '' > "$target_path"
printf '\ndpan_deps\n'                                                                        >> "$target_path"
sqlite3 ~/jzr/hengist/dev/dependency-analyzer/dpan.sqlite "select * from dpan_deps;"          >> "$target_path"
printf '\ndpan_pkg_versions\n'                                                                >> "$target_path"
sqlite3 ~/jzr/hengist/dev/dependency-analyzer/dpan.sqlite "select * from dpan_pkg_versions;"  >> "$target_path"
printf '\ndpan_pkg_names\n'                                                                   >> "$target_path"
sqlite3 ~/jzr/hengist/dev/dependency-analyzer/dpan.sqlite "select * from dpan_pkg_names;"     >> "$target_path"
printf '\ndpan_pkgs\n'                                                                        >> "$target_path"
sqlite3 ~/jzr/hengist/dev/dependency-analyzer/dpan.sqlite "select * from dpan_pkgs;"          >> "$target_path"


