
-- ---------------------------------------------------------------------------------------------------------
insert into tags ( tag, is_block ) values
  ( 'address',      true ),
  ( 'article',      true ),
  ( 'aside',        true ),
  ( 'blockquote',   true ),
  ( 'dd',           true ),
  ( 'details',      true ),
  ( 'dialog',       true ),
  ( 'div',          true ),
  ( 'dl',           true ),
  ( 'dt',           true ),
  ( 'fieldset',     true ),
  ( 'figcaption',   true ),
  ( 'figure',       true ),
  ( 'footer',       true ),
  ( 'form',         true ),
  ( 'h1',           true ),
  ( 'h2',           true ),
  ( 'h3',           true ),
  ( 'h4',           true ),
  ( 'h5',           true ),
  ( 'h6',           true ),
  ( 'header',       true ),
  ( 'hgroup',       true ),
  ( 'li',           true ),
  ( 'main',         true ),
  ( 'nav',          true ),
  ( 'ol',           true ),
  ( 'p',            true ),
  ( 'pre',          true ),
  ( 'section',      true ),
  ( 'table',        true ),
  ( 'ul',           true );

-- ---------------------------------------------------------------------------------------------------------
insert into tags ( tag, is_block, is_empty ) values
  ( 'hr',           true, true );

-- ---------------------------------------------------------------------------------------------------------
insert into tags ( tag, is_empty ) values
  ( 'area',         true ),
  ( 'base',         true ),
  ( 'br',           true ),
  ( 'col',          true ),
  ( 'embed',        true ),
  ( 'img',          true ),
  ( 'input',        true ),
  ( 'link',         true ),
  ( 'meta',         true ),
  ( 'param',        true ),
  ( 'source',       true ),
  ( 'track',        true ),
  ( 'wbr',          true );

-- ---------------------------------------------------------------------------------------------------------
insert or ignore into tags ( tag ) values
  ( 'area'          ),
  ( 'base'          ),
  ( 'br'            ),
  ( 'col'           ),
  ( 'embed'         ),
  ( 'hr'            ),
  ( 'img'           ),
  ( 'input'         ),
  ( 'link'          ),
  ( 'meta'          ),
  ( 'param'         ),
  ( 'source'        ),
  ( 'track'         ),
  ( 'wbr'           ),
  ( 'address'       ),
  ( 'article'       ),
  ( 'aside'         ),
  ( 'blockquote'    ),
  ( 'dd'            ),
  ( 'details'       ),
  ( 'dialog'        ),
  ( 'div'           ),
  ( 'dl'            ),
  ( 'dt'            ),
  ( 'fieldset'      ),
  ( 'figcaption'    ),
  ( 'figure'        ),
  ( 'footer'        ),
  ( 'form'          ),
  ( 'h1'            ),
  ( 'h2'            ),
  ( 'h3'            ),
  ( 'h4'            ),
  ( 'h5'            ),
  ( 'h6'            ),
  ( 'header'        ),
  ( 'hgroup'        ),
  ( 'hr'            ),
  ( 'li'            ),
  ( 'main'          ),
  ( 'nav'           ),
  ( 'ol'            ),
  ( 'p'             ),
  ( 'pre'           ),
  ( 'section'       ),
  ( 'table'         ),
  ( 'ul'            ),
  ( 'a'             ),
  ( 'abbr'          ),
  ( 'acronym'       ),
  ( 'applet'        ),
  ( 'area'          ),
  ( 'audio'         ),
  ( 'b'             ),
  ( 'base'          ),
  ( 'basefont'      ),
  ( 'bdi'           ),
  ( 'bdo'           ),
  ( 'big'           ),
  ( 'body'          ),
  ( 'button'        ),
  ( 'canvas'        ),
  ( 'caption'       ),
  ( 'center'        ),
  ( 'cite'          ),
  ( 'code'          ),
  ( 'col'           ),
  ( 'colgroup'      ),
  ( 'data'          ),
  ( 'datalist'      ),
  ( 'del'           ),
  ( 'dfn'           ),
  ( 'em'            ),
  ( 'embed'         ),
  ( 'font'          ),
  ( 'frame'         ),
  ( 'frameset'      ),
  ( 'head'          ),
  ( 'html'          ),
  ( 'i'             ),
  ( 'iframe'        ),
  ( 'img'           ),
  ( 'input'         ),
  ( 'ins'           ),
  ( 'kbd'           ),
  ( 'keygen'        ),
  ( 'label'         ),
  ( 'legend'        ),
  ( 'link'          ),
  ( 'map'           ),
  ( 'mark'          ),
  ( 'menu'          ),
  ( 'menuitem'      ),
  ( 'meta'          ),
  ( 'meter'         ),
  ( 'noscript'      ),
  ( 'object'        ),
  ( 'optgroup'      ),
  ( 'option'        ),
  ( 'output'        ),
  ( 'param'         ),
  ( 'progress'      ),
  ( 'q'             ),
  ( 'rb'            ),
  ( 'rp'            ),
  ( 'rt'            ),
  ( 'rtc'           ),
  ( 'ruby'          ),
  ( 's'             ),
  ( 'samp'          ),
  ( 'script'        ),
  ( 'select'        ),
  ( 'small'         ),
  ( 'source'        ),
  ( 'span'          ),
  ( 'strike'        ),
  ( 'strong'        ),
  ( 'style'         ),
  ( 'sub'           ),
  ( 'summary'       ),
  ( 'sup'           ),
  ( 'tbody'         ),
  ( 'td'            ),
  ( 'template'      ),
  ( 'textarea'      ),
  ( 'tfoot'         ),
  ( 'th'            ),
  ( 'thead'         ),
  ( 'time'          ),
  ( 'title'         ),
  ( 'tr'            ),
  ( 'track'         ),
  ( 'u'             ),
  ( 'var'           ),
  ( 'video'         ),
  ( 'wbr'           );





